/**C##CARDENAS276_P	

@ULICES CARDENAS LAB 7
TRIGGER #2
*/

CREATE OR REPLACE TRIGGER InsertOrderItemsTRG 
BEFORE INSERT ON ORDERITEMS 
FOR EACH ROW 

DECLARE 
      QTY_TOO_LOW EXCEPTION; 
      PRAGMA EXCEPTION_INIT(QTY_TOO_LOW, -20111);
    
    
BEGIN 
         
       SELECT NVL(MAX(DETAIL),0)+1
       INTO :NEW.DETAIL
       FROM ORDERITEMS
       WHERE ORDERID = :NEW.ORDERID;
      

        
       UPDATE INVENTORY SET STOCKQTY = STOCKQTY - (:NEW.QTY)
       WHERE PARTID = :NEW.PARTID;
       DBMS_OUTPUT.PUT_LINE('UPDATE COMPLETE');
        

EXCEPTION 
        WHEN QTY_TOO_LOW THEN 
        RAISE;
        WHEN OTHERS THEN
        RAISE;
END;
